benchmark:
  - task: RuC
    hdl: sv # sv (SystemVerilog) or v (Verilog)
    dataset_path: # Path to the dataset
    model_path: # Folder containing the models
    output_path: # Folder to store the generation results
    singularity_image: # Singularity image for inference
    evaluation_image: # Singularity image for evaluation and benchmark creation
    models:
      - name: Qwen2.5-Coder-14B
        slurm_config_inference: accelerate-partition-debug
        slurm_config_evaluate: general-partition-debug # SLURM configuration for evaluation and benchmark creation
        precision: bfloat16
        temperature: 0.2
        sequence_length_limit: 32768
        max_tokens: 2048
        top_p: 0.95
        top_k: -1
        n_samples: 1
        gpu_memory_utilization: 0.85
        swap_space: 16
        tensor_parallel_size: 4
        batch_size: 64
        debug: true
      - name: Qwen2.5-Coder-14B-Instruct
        slurm_config_inference: accelerate-partition-debug
        slurm_config_evaluate: general-partition-debug
        precision: bfloat16
        temperature: 0.2
        sequence_length_limit: 32768
        max_tokens: 2048
        top_p: 0.95
        top_k: -1
        n_samples: 1
        gpu_memory_utilization: 0.85
        swap_space: 16
        tensor_parallel_size: 4
        batch_size: 64
        debug: true