configurations:
  - type: general-partition-debug # Name of the SLURM configuration
    account: # SLURM account to use
    qos: # SLURM QoS to use
    output: slurm_output/job_%j.out
    error: slurm_output/job_%j.err
    nodes: 1
    time: "02:00:00"
    ntasks: 1
    cpus-per-task: 80
  - type: accelerate-partition-debug
    account: # SLURM account to use
    qos: # SLURM QoS to use
    output: slurm_output/job_%j.out
    error: slurm_output/job_%j.err
    nodes: 1
    time: "02:00:00"
    gres: gpu:4
    ntasks: 1
    cpus-per-task: 80
    exclusive: true